baseURL = "https://tomscotch.onrender.com"
languageCode = "en-us"
title = "7Days - Showcase"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
#disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "7Days"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false

[[menu.main]]
  name = "Download"
  url = "https://drive.google.com/uc?id=1E7XOREXYZG0imWWR-6pYVmIcU1l4hOx7&export=download"

#[social]
 # facebook = "https://facebook.com"
  #twitter = "https://twitter.com"
  #instagram = "https://instagram.com"
  #linkedin = "https://linkedin.com"
